sudo: false
language: php
php:
  - '5.6'
before_install:
  - composer self-update
  - nvm install 4.8.3
  - nvm use 4.8.3
  - npm --version
  - node --version
  - npm install -g grunt-cli
install:
  - npm install phantomjs
  - npm install caniuse-db
  - npm install
script:
  - grunt coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
